[package]
name = "oyster-cli"
version = "0.14.0"
edition = "2024"
publish = false

[lib]
name = "oyster_cli"
path = "src/lib.rs"

[[bin]]
name = "oyster"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
inquire = "0.9.4"
reqwest = { workspace = true }
rpassword = "7.5.4"
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile.workspace = true
