ALTER TABLE accounts ADD COLUMN min_sui_balance INTEGER NOT NULL DEFAULT 0;
ALTER TABLE accounts ADD COLUMN min_wal_balance INTEGER NOT NULL DEFAULT 0;
ALTER TABLE accounts ADD COLUMN top_up_target_sui INTEGER NOT NULL DEFAULT 0;
ALTER TABLE accounts ADD COLUMN top_up_target_wal INTEGER NOT NULL DEFAULT 0;
