syntax = "proto3";

package pearl;

service Pearl {
  rpc CreateAccount(CreateAccountRequest) returns (CreateAccountResponse);
  rpc GetAddress(GetAddressRequest) returns (GetAddressResponse);
  rpc SignTransaction(SignTransactionRequest) returns (SignTransactionResponse);
}

message CreateAccountRequest {}

message CreateAccountResponse {
  string account_id = 1;
  string address = 2;
}

message GetAddressRequest {
  string account_id = 1;
}

message GetAddressResponse {
  string address = 1;
}

message SignTransactionRequest {
  bytes tx_data = 1;
  string account_id = 2;
}

message SignTransactionResponse {
  bytes signed_transaction = 1;
}
