[package]
name = "pearl"
version = "0.12.1"
edition = "2024"
publish = false

[dependencies]
axum = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
fastcrypto = { workspace = true }
hex = { workspace = true }
hkdf = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
prost = { workspace = true }
sha2 = { workspace = true }
shared-crypto = { workspace = true }
subtle = { workspace = true }
sui-types = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true, features = ["tls-aws-lc"] }
tonic-health = { workspace = true }
tonic-prost = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
zeroize = { workspace = true }

[lints]
workspace = true

[build-dependencies]
tonic-build = { workspace = true }
tonic-prost-build = { workspace = true }

[dev-dependencies]
tokio-stream = { workspace = true }
